### ISSUE TITLE
Differences to source repo

### ISSUE THREAD

**Issue by svscorp** [hrsantiago/docker-dropbox#1]
Hi @hrsantiago 

Curious, what's the difference to https://github.com/otherguy/docker-dropbox and reason for creating this version of docker-dropbox?

**Comment by hrsantiago** [comment]
Hello @svscorp , I didn't see your message before.

Not many differences, it's an old copy from that repo. Once I've updated the Ubuntu version, for example.

Just decided to make it an repository in order to make my life easier with automatic deploys.
